---
development:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: postgres
  database: postgres
  pool: 5
  timeout: 5000
test:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: postgres
  database: postgres
  pool: 5
  timeout: 5000
