development: &development
  cipher: AES-256-CBC
  tasks:
    -
      - example/database.yml
      - example/database.yml.enc
    -
      - example/secrets.yml
      - example/secrets.yml.enc

test:
  <<: *development

production:
  <<: *development
