development: &development
  ev_name: SECRET_KEEPER
  cipher: AES-256-CBC
  tasks:-encrypt_from: example/database.yml
      encrypt_to: example/database.yml.enc
      # decrypt_from: example/database.yml.enc
      # decrypt_to: example/database.yml
    -
      encrypt_from: example/secrets_from_other_source.yml
      encrypt_to: example/secrets.yml.enc
      # decrypt_from: example/secrets.yml.enc
      decrypt_to: example/secrets.yml

  test:
  <<: *development

  production:
  <<: *development
